sonar.projectKey=BrunaABraguin_mindease-app
sonar.projectName=mindease-app
sonar.projectVersion=1.0.0

sonar.sources=lib
sonar.tests=test

sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/firebase_options.dart,**/generated/**,**/build/**,**/*.config.dart,**/*.gen.dart,**/l10n/**

sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
